/**
 * translate_descriptions.js
 * Translates the German HTML descriptions in de_descriptions.json to Arabic.
 * Rules:
 *  - HTML tags / classes / attributes → preserved exactly
 *  - Numbers, €, %, digits → preserved exactly
 *  - Only visible German text → translated
 *  - No non-Arabic characters in output (except HTML syntax, digits, €, %, whitespace)
 */

'use strict';
const fs = require('fs');
const path = require('path');

// ─── Translation Lexicon ─────────────────────────────────────────────────────
// Order matters: longer / more specific phrases first to avoid partial replacements.

const LEXICON = [
  // ── Table headers ─────────────────────────────────────────────────────────
  ['Teilnehmer',                      'المشاركون'],
  ['Fahrzeug',                        'المركبة'],
  ['Preis pro Person',                'السعر للشخص الواحد'],
  ['Reisetyp',                        'نوع الرحلة'],
  ['Reiseantritt',                    'موعد انطلاق الرحلة'],
  ['Abholung',                        'الاستقبال'],
  ['Preis',                           'السعر'],
  ['Boot',                            'القارب'],

  // ── Vehicle types ─────────────────────────────────────────────────────────
  ['Privates Speedboot',              'قارب سريع خاص'],
  ['Private Limousine',               'ليموزين خاصة'],
  ['Privater Minibus',                'حافلة صغيرة خاصة'],

  // ── Person counts (must come before generic "Personen") ───────────────────
  ['1 Person',                        'شخص واحد'],
  ['2 Personen',                      'شخصان'],
  ['3 Personen',                      '3 أشخاص'],
  ['4 Personen',                      '4 أشخاص'],
  ['5 Personen',                      '5 أشخاص'],
  ['6 Personen',                      '6 أشخاص'],
  ['7 Personen',                      '7 أشخاص'],
  ['8 Personen',                      '8 أشخاص'],
  ['3 – 4 Personen',                  '3 – 4 أشخاص'],
  ['5 – 6 Personen',                  '5 – 6 أشخاص'],
  ['7 – 8 Personen',                  '7 – 8 أشخاص'],
  ['3 - 4 Personen',                  '3 – 4 أشخاص'],
  ['5 - 6 Personen',                  '5 – 6 أشخاص'],
  ['7 - 8 Personen',                  '7 – 8 أشخاص'],
  ['Personen',                        'أشخاص'],
  ['Person',                          'شخص'],

  // ── Price patterns ─────────────────────────────────────────────────────────
  // "150 € p.P." → keep number+€, only translate suffix
  // Handled separately via regex below.
  // "Ab 35 € p.P." etc. handled via prefix lexicon entry
  ['p.P.',                            'للشخص الواحد'],
  ['kostenlos',                       'مجاني'],
  ['Kostenlos',                       'مجاني'],
  ['Ab ',                             'من '],

  // ── Time / frequency ──────────────────────────────────────────────────────
  ['täglich',                         'يومياً'],
  ['ca. 8:00 Uhr',                    'نحو الساعة 8:00 صباحاً'],
  ['ca. 12:00 Uhr',                   'نحو الساعة 12:00 ظهراً'],
  ['ca.',                             'نحو'],
  ['Uhr',                             ''],

  // ── Tour type ─────────────────────────────────────────────────────────────
  ['Gruppentour',                     'جولة جماعية'],
  ['Privattour',                      'جولة خاصة'],
  ['Privattours',                     'جولات خاصة'],

  // ── Common nouns & adjectives ─────────────────────────────────────────────
  ['Heißluftballonfahrt',             'رحلة منطاد الهواء الساخن'],
  ['Heißluftballon',                  'منطاد الهواء الساخن'],
  ['Sonnenaufgang',                   'شروق الشمس'],
  ['Sonnenuntergang',                 'غروب الشمس'],
  ['Tagesausflug',                    'رحلة نهارية'],
  ['Tagesausflügen',                  'رحلات نهارية'],
  ['Stadtrundfahrt',                  'جولة المدينة'],
  ['Schnorchelausflug',               'رحلة غطس'],
  ['Schnorchelausflüge',              'رحلات غطس'],
  ['Schnorchelausflügen',             'رحلات غطس'],
  ['Schnorcheln',                     'الغطس'],
  ['Schnorchler',                     'متذوقي الغطس'],
  ['schnorcheln',                     'الغطس'],
  ['Schiffswrack',                    'حطام السفينة'],
  ['Delfinen',                        'الدلافين'],
  ['Delfine',                         'دلافين'],
  ['Delfingebieten',                  'مناطق الدلافين'],
  ['Delfingebiet',                    'منطقة الدلافين'],
  ['Delfin-Sichtungsquote',           'معدل مشاهدة الدلافين'],
  ['Korallenriffe',                   'الشعاب المرجانية'],
  ['Korallenriff',                    'شعاب مرجانية'],
  ['Korallenformationen',             'تكوينات مرجانية'],
  ['Korallenriffen',                  'الشعاب المرجانية'],
  ['Meeresbewohner',                  'الكائنات البحرية'],
  ['Meeresleben',                     'الحياة البحرية'],
  ['Meeresblick',                     'إطلالة على البحر'],
  ['Unterwasserwelt',                 'عالم تحت الماء'],
  ['Nationalpark',                    'المنتزه الوطني'],
  ['Giftun-Nationalpark',             'منتزه الجفتون الوطني'],
  ['Sandstrand',                      'شاطئ رملي'],
  ['Sandstrände',                     'شواطئ رملية'],
  ['Strandrestaurant',                'مطعم على الشاطئ'],
  ['Wasserpark',                      'الحديقة المائية'],
  ['Wassersport',                     'الرياضات المائية'],
  ['Wassersportaktivitäten',          'أنشطة الرياضات المائية'],
  ['Wasseroberfläche',                'سطح الماء'],
  ['Wasserwegen',                     'الممرات المائية'],
  ['Lagunenfahrt',                    'رحلة في البحيرة'],
  ['Lagunenstadt',                    'مدينة البحيرات'],
  ['Lagune',                          'البحيرة'],
  ['Lagunen',                         'البحيرات'],
  ['Aussichtsturm',                   'برج المراقبة'],
  ['Ausblicke',                       'مناظر بانورامية'],
  ['Ausblick',                        'منظر بانورامي'],
  ['Panoramafenster',                 'نوافذ بانورامية'],
  ['Panoramafahrt',                   'رحلة بانورامية'],
  ['Panorama',                        'بانوراما'],
  ['Architektur',                     'الهندسة المعمارية'],
  ['mediterraner Architektur',        'هندسة معمارية متوسطية'],
  ['Hafen',                           'ميناء'],
  ['Hafenstädte',                     'مدن الموانئ'],
  ['Hafenstadt',                      'مدينة ميناء'],
  ['Jachthafen',                      'مارينا اليخوت'],
  ['Märkte',                          'الأسواق'],
  ['Marktleben',                      'حياة السوق'],
  ['Moschee',                         'المسجد'],
  ['Große Moschee',                   'المسجد الكبير'],
  ['Café',                            'مقهى'],
  ['ägyptischen Café',                'مقهى مصري'],
  ['Basar',                           'البازار'],
  ['Klöster',                         'الأديرة'],
  ['Kloster',                         'الدير'],
  ['Mönche',                          'الرهبان'],
  ['Mönchtum',                        'الرهبنة'],
  ['Eremit',                          'الناسك'],
  ['Tempel',                          'المعبد'],
  ['Tempelkomplex',                   'مجمع المعابد'],
  ['Tempelstätten',                   'مواقع المعابد'],
  ['Tempelstätte',                    'موقع معبد'],
  ['Pyramiden',                       'الأهرامات'],
  ['Pyramide',                        'الهرم'],
  ['Stufenpyramide',                  'هرم زوسر المدرج'],
  ['Grabmäler',                       'المقابر'],
  ['Gräber',                          'قبور'],
  ['Grab',                            'قبر'],
  ['Mumie',                           'مومياء'],
  ['Reliefs',                         'النقوش'],
  ['Reliefdarstellungen',             'نقوش التصوير'],
  ['Relief',                          'النقش'],
  ['Hieroglyphen',                    'الكتابات الهيروغليفية'],
  ['Säulenhallen',                    'قاعات الأعمدة'],
  ['Säulenhalle',                     'قاعة أعمدة'],
  ['Terrassentempel',                 'معبد الشرفة'],
  ['Hatschepsut-Tempel',              'معبد حتشبسوت'],
  ['Karnak-Tempel',                   'معبد الكرنك'],
  ['Hathor-Tempel',                   'معبد حتحور'],
  ['Tal der Könige',                  'وادي الملوك'],
  ['Niltal',                          'وادي النيل'],
  ['Nilfahrt',                        'رحلة نيلية'],
  ['Memnonkolosse',                   'تمثالا ممنون'],
  ['Königsliste',                     'قائمة الملوك'],
  ['Pharaonen',                       'الفراعنة'],
  ['Pharao',                          'الفرعون'],
  ['Ägyptologen',                     'عالم مصريات'],
  ['Ägyptologe',                      'عالم مصريات'],
  ['deutschsprachigen Ägyptologen',   'عالم مصريات ناطق بالألمانية'],
  ['deutschsprachigen',               'الناطق بالألمانية'],
  ['deutschsprachig',                 'ناطق بالألمانية'],
  ['Deutschsprachig',                 'ناطق بالألمانية'],
  ['Reiseleitung',                    'المرشد السياحي'],
  ['Reiseleiter',                     'المرشد السياحي'],
  ['Guide',                           'مرشد سياحي'],
  ['Guides',                          'مرشدون سياحيون'],
  ['Kapitän',                         'القبطان'],
  ['Kapitäne',                        'القباطنة'],
  ['Crew',                            'الطاقم'],
  ['Hotelübernachtung',               'إقامة في الفندق'],
  ['Übernachtung',                    'إقامة ليلية'],
  ['Abendessen',                      'العشاء'],
  ['Frühstück',                       'الإفطار'],
  ['Mittagessen',                     'الغداء'],
  ['Eintrittskarten',                 'تذاكر الدخول'],
  ['Eintrittskarte',                  'تذكرة دخول'],
  ['Eintrittsgelder',                 'رسوم الدخول'],
  ['Transfers',                       'الانتقالات'],
  ['Transfer',                        'انتقال'],
  ['Hoteltransfer',                   'نقل الفندق'],
  ['Hotelabholung',                   'استقبال من الفندق'],
  ['Minibus',                         'حافلة صغيرة'],
  ['Speedboote',                      'قوارب سريعة'],
  ['Speedboot',                       'قارب سريع'],
  ['Bootstour',                       'رحلة بالقارب'],
  ['Bootstransfer',                   'نقل بالقارب'],
  ['Bootsfahrt',                      'رحلة بالقارب'],
  ['Bootsfahrten',                    'رحلات بالقارب'],
  ['Boot',                            'قارب'],
  ['Booten',                          'قوارب'],
  ['Boote',                           'قوارب'],
  ['Schwimmweste',                    'سترة النجاة'],
  ['Schwimmwesten',                   'سترات النجاة'],
  ['Schnorchel',                      'أداة الغطس'],
  ['Sonnencreme',                     'واقي الشمس'],
  ['Sonnenbrille',                    'نظارات شمسية'],
  ['Kopfbedeckung',                   'قبعة'],
  ['Handtuch',                        'منشفة'],
  ['Badebekleidung',                  'ملابس السباحة'],
  ['Jacke',                           'سترة'],
  ['Kleingeld',                       'تغيير صغير'],
  ['Trinkgeld',                       'إكرامية'],
  ['Trinkgelder',                     'إكراميات'],
  ['Toiletten',                       'دورات المياه'],

  // ── Adjectives / phrases ──────────────────────────────────────────────────
  ['kristallklarem Wasser',           'مياه صافية كالكريستال'],
  ['kristallklares Wasser',           'مياه صافية كالكريستال'],
  ['türkisfarbenes Wasser',           'مياه فيروزية'],
  ['türkisfarbenen',                  'الفيروزية'],
  ['türkisfarbene',                   'فيروزية'],
  ['türkisfarbenes',                  'فيروزي'],
  ['türkisfarbenen Wasserwegen',      'الممرات المائية الفيروزية'],
  ['türkisblauen Wasserwegen',        'الممرات المائية الفيروزية'],
  ['türkisblauen',                    'الفيروزية'],
  ['weißem Sandstrand',               'شاطئ رملي أبيض'],
  ['weißer Sand',                     'رمال بيضاء'],
  ['Weicher, weißer Sand',            'رمال بيضاء ناعمة'],
  ['Weiße Sandstrände',               'شواطئ رملية بيضاء'],
  ['farbenprächtige Korallenriffe',   'شعاب مرجانية ملونة'],
  ['farbenprächtig',                  'ملون'],
  ['farbenreichen',                   'ملونة'],
  ['farbenfrohe',                     'ملونة'],
  ['farbenfrohen',                    'ملونة'],
  ['farbintensiven',                  'غنية بالألوان'],
  ['einzigartigen',                   'فريدة من نوعها'],
  ['einzigartiger',                   'فريدة من نوعها'],
  ['einzigartige',                    'فريدة من نوعها'],
  ['einzigartig',                     'فريد من نوعه'],
  ['beeindruckendsten',               'الأكثر إثارة للإعجاب'],
  ['beeindruckendste',                'الأكثر إثارة للإعجاب'],
  ['beeindruckenden',                 'رائعة'],
  ['beeindruckende',                  'رائعة'],
  ['beeindruckend',                   'مثير للإعجاب'],
  ['faszinierende',                   'الرائعة'],
  ['faszinierenden',                  'الرائعة'],
  ['faszinierendes',                  'رائع'],
  ['faszinierend',                    'رائع'],
  ['außergewöhnlicher',               'غير عادية'],
  ['außergewöhnliche',                'غير عادية'],
  ['außergewöhnlich',                 'غير عادي'],
  ['hervorragender',                  'ممتازة'],
  ['hervorragenden',                  'ممتازة'],
  ['hervorragende',                   'ممتازة'],
  ['hervorragend',                    'ممتاز'],
  ['farbenprächtigsten',              'الأكثر إشراقاً'],
  ['farbenprächtigste',               'الأكثر إشراقاً'],
  ['aussagekräftigsten',              'الأكثر دلالة'],
  ['aussagekräftigste',               'الأكثر دلالة'],
  ['ptolemäisch-römischen',           'البطلمي الروماني'],
  ['frühen Mönchtum',                 'الرهبنة المبكرة'],
  ['frühen',                          'المبكر'],
  ['koptische',                       'القبطية'],
  ['koptischen',                      'القبطية'],
  ['christlichen',                    'المسيحية'],
  ['christlicher',                    'المسيحية'],
  ['spirituellen',                    'الروحاني'],
  ['spirituelle',                     'الروحانية'],
  ['spiritueller',                    'روحاني'],
  ['spirituell',                      'روحاني'],
  ['landschaftlich reizvollen',       'ذات مناظر خلابة'],
  ['landschaftlich',                  'طبيعي'],
  ['malerischer',                     'خلابة'],
  ['entspannten',                     'مريحة'],
  ['entspannte',                      'مريحة'],
  ['entspannter',                     'مريح'],
  ['entspannt',                       'مريح'],
  ['bequeme',                         'مريحة'],
  ['bequemen',                        'مريح'],
  ['bequem',                          'مريح'],
  ['komfortablen',                    'المريحة'],
  ['komfortable',                     'مريحة'],
  ['komfortablem',                    'مريح'],
  ['komfortabel',                     'مريح'],
  ['individuell',                     'فردي'],
  ['individuellen',                   'الفردية'],
  ['persönlich',                      'شخصي'],
  ['persönliche',                     'شخصية'],
  ['persönlichen',                    'الشخصية'],
  ['privat',                          'خاص'],
  ['privaten',                        'الخاصة'],
  ['private',                         'خاصة'],
  ['privatem',                        'خاص'],
  ['hochwertige',                     'عالية الجودة'],
  ['hochwertigen',                    'عالية الجودة'],
  ['hochwertigem',                    'عالية الجودة'],
  ['hochwertig',                      'عالي الجودة'],
  ['exklusiver',                      'حصرية'],
  ['exklusive',                       'حصرية'],
  ['exklusiven',                      'الحصرية'],
  ['exklusiv',                        'حصري'],
  ['professioneller',                 'احترافية'],
  ['professionelle',                  'احترافية'],
  ['professionellen',                 'الاحترافية'],
  ['professionell',                   'احترافي'],
  ['erstklassigem',                   'من الدرجة الأولى'],
  ['erstklassige',                    'من الدرجة الأولى'],
  ['erstklassigen',                   'من الدرجة الأولى'],
  ['erstklassig',                     'من الدرجة الأولى'],
  ['unvergesslichen',                 'لا تنسى'],
  ['unvergessliche',                  'لا تنسى'],
  ['unvergesslich',                   'لا تُنسى'],
  ['sicheren',                        'آمنة'],
  ['sichere',                         'آمنة'],
  ['sicher',                          'آمن'],
  ['natürlich',                       'طبيعي'],
  ['natürliche',                      'طبيعية'],
  ['respektvoll',                     'محترم'],
  ['häufig',                          'كثيراً'],
  ['täglich',                         'يومياً'],
  ['früh morgens',                    'في الصباح الباكر'],
  ['früh',                            'مبكراً'],
  ['morgens',                         'في الصباح'],

  // ── Action verbs / imperative phrases ────────────────────────────────────
  ['Entdecken Sie',                   'اكتشف'],
  ['Erleben Sie',                     'استمتع بـ'],
  ['Genießen Sie',                    'استمتع بـ'],
  ['Stellen Sie sich vor',            'تخيل'],
  ['Freuen Sie sich auf',             'انتظر'],
  ['Begleitet von',                   'برفقة'],
  ['Begleitet',                       'برفقة'],
  ['erkunden Sie',                    'استكشف'],
  ['erleben Sie',                     'استمتع بـ'],
  ['entdecken',                       'اكتشاف'],
  ['Entdecken',                       'اكتشف'],
  ['erleben',                         'تجربة'],
  ['besuchen',                        'زيارة'],
  ['besuchen Sie',                    'قم بزيارة'],
  ['Besuchen',                        'زيارة'],
  ['Schwimmen Sie',                   'اسبح'],
  ['schwimmen',                       'السباحة'],
  ['Tauchen Sie ein',                 'انغمس'],
  ['tauchen',                         'الغوص'],
  ['schnorcheln',                     'الغطس'],
  ['ausrüsten',                       'تجهيز'],
  ['genießen',                        'الاستمتاع بـ'],
  ['verbinden',                       'يجمع'],
  ['kombiniert',                      'تجمع'],
  ['kombinieren',                     'جمع'],
  ['reisen',                          'السفر'],
  ['reisen Sie',                      'يمكنك السفر'],
  ['führt',                           'يقود'],

  // ── Sentence openers / connectors ────────────────────────────────────────
  ['Willkommen bei',                  'مرحباً بكم في'],
  ['Willkommen',                      'مرحباً'],
  ['Ein unvergesslicher Tag',         'يوم لا يُنسى'],
  ['Anders als',                      'على عكس'],
  ['Genau zu dieser Zeit',            'في هذا الوقت بالضبط'],
  ['Bis heute',                       'حتى يومنا هذا'],
  ['Hier erwarten Sie',               'هنا تنتظرك'],
  ['Hier erwartet Sie',               'هنا تنتظرك'],
  ['Hier verbinden sich',             'هنا تتجمع'],
  ['Hier erwartet Sie',               'هنا تنتظرك'],
  ['Hier können Sie',                 'هنا يمكنك'],
  ['Hier',                            'هنا'],
  ['Für viele Gäste',                 'لكثير من الضيوف'],
  ['für Gäste',                       'للضيوف'],
  ['für Paare',                       'للأزواج'],
  ['für Familien',                    'للعائلات'],
  ['für Familien, Paare',             'للعائلات والأزواج'],
  ['Familien, Paare und',             'للعائلات والأزواج و'],
  ['Paare, Familien',                 'الأزواج والعائلات'],
  ['Paare',                           'أزواج'],
  ['Familien',                        'عائلات'],
  ['Freunden',                        'الأصدقاء'],
  ['Gruppen',                         'مجموعات'],
  ['kleinen Gruppen',                 'مجموعات صغيرة'],
  ['Anfänger',                        'مبتدئين'],
  ['Anfängern',                       'المبتدئين'],
  ['Nichtschwimmern',                 'غير السباحين'],
  ['Nichtschwimmer',                  'غير السباح'],
  ['Genießer',                        'عشاق الجمال'],
  ['Gäste',                           'الضيوف'],
  ['Gästen',                          'الضيوف'],
  ['Gast',                            'الضيف'],
  ['Reisende',                        'المسافرون'],
  ['Reisenden',                       'المسافرين'],
  ['Geschichtsliebhaber',             'محبي التاريخ'],
  ['Geschichtsinteressierte',         'هواة التاريخ'],
  ['kulturinteressierte',             'المهتمين بالثقافة'],
  ['Christen',                        'المسيحيون'],

  // ── Questions / headings ──────────────────────────────────────────────────
  ['Warum dieser Ausflug so beliebt ist',         'لماذا تحظى هذه الرحلة بشعبية'],
  ['Warum dieser Ausflug zu den besten',          'لماذا تُعدّ هذه الرحلة من أفضل'],
  ['Warum diese Tour zu den meistgebuchten',      'لماذا تُعدّ هذه الجولة من أكثر الرحلات حجزاً'],
  ['Warum der Dendera Tempel ein unverzichtbares','لماذا يُعدّ معبد دندرة وجهة لا غنى عنها'],
  ['Warum dieser Ausflug so besonders ist',       'لماذا تتميز هذه الرحلة'],
  ['Für wen eignet sich dieser Ausflug?',         'لمن تناسب هذه الرحلة؟'],
  ['Für wen eignet sich',                         'لمن تناسب'],
  ['Warum',                                       'لماذا'],
  ['Reisetipps für Ihren Ausflug',                'نصائح سفر لرحلتك'],
  ['Reisetipps',                                  'نصائح السفر'],
  ['Bitte mitbringen',                            'يُرجى إحضار'],
  ['Höhepunkte',                                  'أبرز المعالم'],
  ['Highlight',                                   'أبرز'],

  // ── "In Hurghada" / location ──────────────────────────────────────────────
  ['Hurghada Reiseplaner',            'مخطِّط رحلات الغردقة'],
  ['HurghadaReiseplaner',             'مخطِّط رحلات الغردقة'],
  ['Hurghada Reiseplaner',            'مخطِّط رحلات الغردقة'],
  ['ab Hurghada',                     'من الغردقة'],
  ['in Hurghada',                     'في الغردقة'],
  ['von Hurghada',                    'من الغردقة'],
  ['nach Hurghada',                   'إلى الغردقة'],
  ['Hurghada',                        'الغردقة'],
  ['El Gouna',                        'الجونة'],
  ['Luxor',                           'الأقصر'],
  ['Kairo',                           'القاهرة'],
  ['Ägyptens',                        'مصر'],
  ['Ägypten',                         'مصر'],
  ['ägyptischer',                     'مصرية'],
  ['ägyptische',                      'مصرية'],
  ['ägyptischen',                     'المصرية'],
  ['Roten Meer',                      'البحر الأحمر'],
  ['Roten Meeres',                    'البحر الأحمر'],

  // ── Numbers / time words ──────────────────────────────────────────────────
  ['einzigen',                        'واحد فقط'],
  ['nur einem Tag',                   'يوم واحد فقط'],
  ['nur 4 Stunden',                   'أربع ساعات فقط'],
  ['in nur',                          'في'],
  ['an nur einem',                    'في'],
  ['mindestens',                      'على الأقل'],
  ['maximal',                         'بحد أقصى'],
  ['Maximal',                         'بحد أقصى'],
  ['Minimal',                         'بحد أدنى'],
  ['Stunden',                         'ساعات'],
  ['Stunde',                          'ساعة'],
  ['Minuten',                         'دقيقة'],
  ['Minute',                          'دقيقة'],
  ['Tagen',                           'أيام'],
  ['Tag',                             'يوم'],

  // ── Misc / sentence fillers ───────────────────────────────────────────────
  ['weit mehr als',                   'أكثر بكثير من'],
  ['weit mehr',                       'أكثر بكثير'],
  ['weit',                            'بعيداً'],
  ['noch weit mehr',                  'أكثر من ذلك بكثير'],
  ['noch mehr',                       'أكثر'],
  ['und noch',                        'وأيضاً'],
  ['dafür',                           'لذا'],
  ['ohne',                            'بدون'],
  ['mit',                             'مع'],
  ['und',                             'و'],
  ['oder',                            'أو'],
  ['auch',                            'أيضاً'],
  ['ideal',                           'مثالي'],
  ['ideale',                          'مثالية'],
  ['idealen',                         'المثالية'],
  ['Ideale',                          'مثالية'],
  ['perfekt',                         'مثالي'],
  ['perfekte',                        'مثالية'],
  ['perfekten',                       'المثالية'],
  ['Im Winter',                       'في الشتاء'],
  ['im Winter',                       'في الشتاء'],
  ['wie',                             'مثل'],
  ['als',                             'كـ'],
  ['sowie',                           'وكذلك'],
  ['bereits',                         'بالفعل'],
  ['jederzeit',                       'في جميع الأوقات'],
  ['sofort',                          'فوراً'],
  ['genau',                           'بالضبط'],
  ['selbst',                          'بنفسك'],
  ['einmal',                          'مرة واحدة'],
  ['besonders',                       'بشكل خاص'],
  ['Besonders',                       'بشكل خاص'],
  ['typisch',                         'نموذجي'],
  ['typische',                        'نموذجية'],
  ['typischen',                       'النموذجية'],
  ['ebenso',                          'بالمثل'],
  ['tatsächlich',                     'في الواقع'],
  ['hier',                            'هنا'],
  ['dort',                            'هناك'],
  ['direkt',                          'مباشرة'],
  ['inklusive',                       'شامل'],
  ['Inklusive',                       'شامل'],
  ['inbegriffen',                     'متضمن'],
  ['bereits im Preis enthalten',      'مشمول في السعر'],
  ['im Preis enthalten',              'مشمول في السعر'],
  ['enthalten',                       'متضمن'],
  ['Möglichkeit',                     'إمكانية'],
  ['Möglichkeiten',                   'إمكانيات'],
  ['Kombination',                     'مجموعة'],
  ['kombiniert',                      'تجمع'],
  ['Atmosphäre',                      'أجواء'],
  ['Abendatmosphäre',                 'أجواء المساء'],
  ['Abendrhythmus',                   'الإيقاع المسائي'],
  ['Abend',                           'المساء'],
  ['abends',                          'في المساء'],
  ['Nacht',                           'الليل'],
  ['nachts',                          'في الليل'],
  ['nächtliche',                      'الليلية'],
  ['Abenteuer',                       'مغامرة'],
  ['Erholung',                        'الاسترخاء'],
  ['Erlebnis',                        'تجربة'],
  ['Erlebnisse',                      'تجارب'],
  ['Erlebnisses',                     'التجربة'],
  ['Eindrücke',                       'انطباعات'],
  ['Eindrücken',                      'انطباعات'],
  ['Einblicke',                       'رؤى'],
  ['Sehenswürdigkeiten',              'المعالم السياحية'],
  ['Sehenswürdigkeit',                'معلم سياحي'],
  ['Kulturdenkmäler',                 'المعالم الثقافية'],
  ['Kulturdenkmal',                   'معلم ثقافي'],
  ['Kulturreisen',                    'الرحلات الثقافية'],
  ['Kulturreise',                     'رحلة ثقافية'],
  ['Touristenrouten',                 'المسارات السياحية'],
  ['Touristenroute',                  'مسار سياحي'],
  ['Touristenattraktion',             'موقع سياحي'],
  ['Touristenattraktionen',           'المواقع السياحية'],
  ['Komfort',                         'الراحة'],
  ['Qualität',                        'الجودة'],
  ['Sicherheit',                      'الأمان'],
  ['Ruhe',                            'الهدوء'],
  ['Harmonie',                        'التناسق'],
  ['Luxus',                           'الفخامة'],
  ['Geschichte',                      'التاريخ'],
  ['historischen',                    'التاريخية'],
  ['historische',                     'تاريخية'],
  ['historisch',                      'تاريخي'],
  ['Religion',                        'الدين'],
  ['religiöser',                      'دينية'],
  ['religiöse',                       'دينية'],
  ['religiös',                        'ديني'],
  ['Tradition',                       'التقليد'],
  ['Traditionen',                     'التقاليد'],
  ['tradtionell',                     'تقليدي'],
  ['traditionellen',                  'التقليدية'],
  ['traditionelle',                   'تقليدية'],
  ['traditionell',                    'تقليدي'],
  ['original',                        'أصلي'],
  ['Original',                        'أصلي'],
  ['ursprünglich',                    'أصلي'],
  ['ursprüngliche',                   'الأصلية'],
  ['Originalfarben',                  'الألوان الأصلية'],
  ['authentische',                    'أصيلة'],
  ['authentischen',                   'الأصيلة'],
  ['authentisch',                     'أصيل'],
  ['Jahrhunderten',                   'قرون'],
  ['Jahrhundert',                     'قرن'],
  ['Jahrtausenden',                   'آلاف السنين'],
  ['Jahrtausende',                    'آلاف السنين'],
  ['jahrtausendealten',               'التي مضى عليها آلاف السنين'],
  ['jahrhundertealten',               'التي مضى عليها قرون'],
  ['altägyptischen',                  'المصرية القديمة'],
  ['altägyptischer',                  'مصرية قديمة'],
  ['altägyptisches',                  'مصري قديم'],
  ['alten Ägyptens',                  'مصر القديمة'],
  ['Alten Ägyptens',                  'مصر القديمة'],
  ['alten',                           'القديم'],
  ['Alten',                           'القديم'],
  ['antiken',                         'القديمة'],
  ['antike',                          'قديمة'],
  ['antik',                           'قديم'],
  ['lebendige',                       'نابض بالحياة'],
  ['lebendig',                        'نابض بالحياة'],
  ['lebendig',                        'نابض بالحياة'],
  ['farbenfroh',                      'ملون'],
  ['bunte',                           'ملونة'],
  ['bunt',                            'ملون'],
  ['Farben',                          'الألوان'],
  ['Farbe',                           'اللون'],
  ['Licht',                           'الضوء'],
  ['beleuchtet',                      'مضاءة'],
  ['beleuchtete',                     'مضاءة'],
  ['leuchtend',                       'متلألئ'],
  ['Preis-Leistungs-Verhältnis',      'قيمة مقابل المال'],
  ['Meeresblick',                     'إطلالة على البحر'],
  ['Massenbetrieb',                   'الاكتظاظ السياحي'],
  ['Massentourismus',                 'السياحة الجماعية'],
  ['Massenboote',                     'قوارب جماعية'],
  ['Massengruppen',                   'المجموعات الكبيرة'],
  ['Massenbus',                       'حافلة جماعية'],
  ['Verkaufsstopps',                  'توقفات للبيع'],
  ['Zeitdruck',                       'ضغط الوقت'],
  ['Gedränge',                        'الازدحام'],
  ['Hektik',                          'صخب'],
  ['unberührt',                       'لم تمسها يد الإنسان'],
  ['unberührte',                      'بكر'],
  ['geschützt',                       'محمية'],
  ['geschützten',                     'المحمية'],
  ['geschützter',                     'محمية'],
  ['abgeschieden',                    'نائية'],
  ['abgeschiedenen',                  'النائية'],
  ['inmitten',                        'في وسط'],
  ['unweit',                          'قريباً من'],
  ['nördlich',                        'شمال'],
  ['südlich',                         'جنوب'],
  ['östlich',                         'شرق'],
  ['westlich',                        'غرب'],
  ['entlang',                         'على طول'],
  ['hinter',                          'خلف'],
  ['vor',                             'قبل'],
  ['nach',                            'بعد'],
  ['über',                            'فوق'],
  ['unter',                           'تحت'],
  ['zwischen',                        'بين'],
  ['neben',                           'بجانب'],
  ['gegenüber',                       'مقابل'],
  ['in der Nähe',                     'بالقرب من'],
  ['rund',                            'حوالي'],
  ['etwa',                            'نحو'],
  ['ungefähr',                        'تقريباً'],
  ['nur',                             'فقط'],
  ['sehr',                            'جداً'],
  ['oft',                             'غالباً'],
  ['oft selbst',                      'في الغالب بنفسها'],
  ['viele',                           'كثيرة'],
  ['viel',                            'كثير'],
  ['wenige',                          'قليل'],
  ['wenig',                           'قليل'],
  ['weitere',                         'إضافية'],
  ['weiteren',                        'إضافية'],
  ['alle',                            'جميع'],
  ['All',                             'جميع'],
  ['alles',                           'كل شيء'],
  ['keine',                           'لا'],
  ['kein',                            'لا'],
  ['keiner',                          'لا'],
  ['keinen',                          'لا'],
  ['nicht',                           'لا'],
  ['nie',                             'أبداً'],
  ['mehr',                            'المزيد'],
  ['weniger',                         'أقل'],
  ['immer',                           'دائماً'],
  ['sogar',                           'حتى'],
  ['Ihr',                             'مسيرك'],
  ['Ihre',                            'مسيرك'],
  ['Ihnen',                           'لك'],
  ['Ihrem',                           'مسيرك'],
  ['Sie',                             'يمكنك'],
  ['wir',                             'نحن'],
  ['Wir',                             'نحن'],
  ['uns',                             'لنا'],
  ['sich',                            ''],
  ['dem',                             'الـ'],
  ['den',                             'الـ'],
  ['das',                             'الـ'],
  ['die',                             'الـ'],
  ['der',                             'الـ'],
  ['des',                             'الـ'],
  ['ein',                             ''],
  ['eine',                            ''],
  ['einem',                           ''],
  ['einer',                           ''],
  ['einen',                           ''],
  ['ist',                             'هو'],
  ['sind',                            'هم'],
  ['war',                             'كان'],
  ['waren',                           'كانوا'],
  ['wird',                            'يصبح'],
  ['werden',                          'يصبحون'],
  ['haben',                           'يمتلك'],
  ['hat',                             'يمتلك'],
  ['kann',                            'يمكن'],
  ['können',                          'يمكن'],
  ['gilt',                            'يُعدّ'],
  ['gelten',                          'تُعدّ'],
  ['bietet',                          'يوفر'],
  ['bieten',                          'توفر'],
  ['bringt',                          'يجلب'],
  ['bringen',                         'تجلب'],
  ['schätzen',                        'تقدّر'],
  ['möchten',                         'ترغب'],
  ['möchte',                          'تريد'],
  ['wollen',                          'تريد'],
  ['geführten',                       'المنظمة'],
  ['geführte',                        'منظمة'],
  ['geführt',                         'منظم'],
  ['geleitet',                        'يقود'],
  ['stattgefunden',                   'أجريت'],
  ['Preis-Leistungs-Verhältnis',      'قيمة مقابل المال'],
];

// ─── HTML-aware text replacement ─────────────────────────────────────────────
/**
 * Split HTML into alternating [text, tag, text, tag, ...] segments.
 * Only translate the "text" segments (even indices).
 */
function translateHtml(html) {
  // Split by tags: keep delimiters so we can reconstruct
  const parts = html.split(/(<[^>]+>)/);
  // parts[0], [2], [4] = text; parts[1], [3], [5] = tags
  const result = parts.map((part, idx) => {
    if (idx % 2 === 1) return part; // tag → keep as-is
    return translateText(part);
  });
  return result.join('');
}

/**
 * Apply lexicon substitutions to a plain-text segment.
 * Preserve: numbers, €, %, p.P., ASCII punctuation in HTML attributes (already excluded).
 * Strategy: replace longest matches first (lexicon is ordered), word-boundary aware.
 */
function translateText(text) {
  if (!text.trim()) return text;

  for (const [de, ar] of LEXICON) {
    if (!de) continue;
    // Escape special regex chars in the German phrase
    const escaped = de.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // Use word boundary or whitespace/start/end
    try {
      const re = new RegExp(`(?<![\\w\u0600-\u06ff])${escaped}(?![\\w\u0600-\u06ff])`, 'g');
      text = text.replace(re, ar);
    } catch (e) {
      // Fallback: simple string replace
      text = text.split(de).join(ar);
    }
  }

  // Post-process: clean up double whitespace, stray "– –"
  text = text.replace(/  +/g, ' ');
  text = text.replace(/الـ\s+الـ/g, 'الـ');
  // Remove trailing/leading whitespace-only artifacts on each line
  text = text.split('\n').map(l => l.trimEnd()).join('\n');

  return text;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
const inputFile  = path.join(__dirname, 'de_descriptions.json');
const outputFile = path.join(__dirname, 'ar_descriptions_translated.json');

const entries = JSON.parse(fs.readFileSync(inputFile, 'utf8'));
const results = [];

for (const entry of entries) {
  const arHtml = translateHtml(entry.de_description);
  results.push({
    id: entry.id,
    shortId: entry.shortId,
    table: entry.table,
    ar_description: arHtml,
    de_description: entry.de_description,  // keep for cross-reference
  });
}

fs.writeFileSync(outputFile, JSON.stringify(results, null, 2), 'utf8');
console.log(`Translated ${results.length} descriptions → ${outputFile}`);
console.log('\n=== SAMPLE 1 (Private tour – Luxor, full pricing table) ===');
const s1 = results.find(r => r.shortId === '42a2941f');
if (s1) console.log(s1.ar_description);
console.log('\n=== SAMPLE 2 (Group tour – Glass-bottom boat) ===');
const s2 = results.find(r => r.shortId === '0009b90b');
if (s2) console.log(s2.ar_description);
console.log('\n=== SAMPLE 3 (Speedboat dolphin – different column headers) ===');
const s3 = results.find(r => r.shortId === '27ae0b35');
if (s3) console.log(s3.ar_description);
